sudo: required
dist: trusty
language: java
jdk:
- openjdk11
branches:
  only:
  - develop
  - master
notifications:
  slack:
    on_success: change
    on_failure: always
    secure: Tddv/PyRCjTrektnonH1ZniR3Sf3xlz547LrHJUKeJ0pMcFNJTYzxXJfvF+ozocVOok4rwW9xPBscHEZLZM8UnAwRPiGQ2gECc8b35AjjBQ8zFuWLsKBkmpHV9Sd3PHRb8ejvcX4nrdnygdzLL5pZHM8vM/O8M57QVowHTn2ZL+J2bFT0W264ffSet62FzKz+8LaCsPs4ix5eUhVT30vbJl1NGTju5jzz8azmvALdfuTzdIy5HKu8Lu20pJvLi7/J21YtHoSjCmf1hq+/Kf7IH5/GvF4YkT1927Sn0I0kG3Xrb8Xrbuhq0INJ11VtwQlUjBZbZgQ4yykOVotPybDAGshU3QKTzD6bWBpLDxuv/gYgrUB0H6Pk899Al/wq7M2oFxWrjtmtKN/aFJ3DPiduPVP1O6wAdDskxLTIT0zB0mQq+S/89MXnxJoCSTKdkGx6Ol7zdi6zBw5Eg5CLE1xZ3pICA30kfb26QVGxHDduWRg/TgsAtn1FKkMQmni9JOjzVmO9Ir8w5a6bdSM/qHXKV3D2rmmEBQPoidQOM4FVYH7RlcKPEaV5tS97gHabqR1flh8N0IDTxvNZNL8me0qXyjy9JpiDKt+r3BefU7hRbYeD431MFGlVT7FOZ1CpKXWJOubZv/ZgwVbZ0gvWwhQftj2D5bEFYZ3iBhItPclotU=
install: '[ ${TRAVIS_PULL_REQUEST} = ''false'' ] && mvn -DskipTests=false clean deploy
  --settings .m2/travis-settings.xml'
script: '[ ${TRAVIS_PULL_REQUEST} = ''false'' ] && mvn -DskipTests=true clean --settings
  .m2/travis-settings.xml'
env:
  global:
  - CEDAR_HOST=metadatacenter.orgx
  - CEDAR_ADMIN_USER_API_KEY=1234
  - CEDAR_MONGO_APP_USER_NAME=cedarUser
  - CEDAR_MONGO_APP_USER_PASSWORD=password
  - CEDAR_NEO4J_HOST=127.0.0.1
  - CEDAR_NEO4J_BOLT_PORT=7687
  - CEDAR_NEO4J_USER_NAME=neo4j
  - CEDAR_NEO4J_USER_PASSWORD=neo4j
  - CEDAR_MESSAGING_MYSQL_HOST=127.0.0.1
  - CEDAR_MESSAGING_MYSQL_PORT=3306
  - CEDAR_MESSAGING_MYSQL_DB=cedar_messaging
  - CEDAR_MESSAGING_MYSQL_USER=cedar_messaging_user
  - CEDAR_MESSAGING_MYSQL_PASSWORD=cedar_messaging_password
  - CEDAR_USER_HTTP_PORT=9005
  - CEDAR_MESSAGING_HTTP_PORT=9012
  - CEDAR_MESSAGING_ADMIN_PORT=9112
  - CEDAR_MESSAGING_STOP_PORT=9212
  - CEDAR_TEST_USER1_ID=https://metadatacenter.org/users/user1-uuid
  - CEDAR_TEST_USER2_ID=https://metadatacenter.org/users/user2-uuid
  - secure: MeseOJTa0e1sgCqSeT02XeLlVisAD2othy+zK9h3v10cBNhCxNHtYb4gvIKrMum38C0DLY1BEfcjtwqOfogXXVDAokTcIPkIEAg5tvFJ4RqtcEcA1lCcPwjKRMBrl2vFbhP63uzemJ7uhjHRe4vDK1gi7eMmYLVfGdxEkpZIwR+fEAAF01A8j+0t2HZSOrrQLKAR/tKGBzuxNhEZxe6HthgQaSA+NqYBkU+jfZEYk+6aYc8RnjWk/jU+oMcZoRTGsXw/IwdPF8L38BPWdT5TxrKmBS1sUkIpjGx5W4e4NpWqzV8jB/kwflhsclT/q4eEL/n1dE2n0J+ocGSgL/YIzjSb6jpRwdkEab9+aGXnKwo/PXc9wBdSjf/UahweO38UtIbQ9f1OZUbOpTkWhkY0jfZsTo/v17HJ5teP9MarAvEvy1UYHYBtu7ajpMpCW4CEu53oa9k8NMcJ2Hi1AQS/UxgLHdw4zf19+PzhMH7NVf84iJp+82vS7X+qVHTN842YyF3Oy2B6wIV66EaIVc4awvYb5+IbuwZfUqOC6R2EOBjPqbGeFqePFfTMourM+QaiOgA1zPWLLPqNCz5MEA+4XOk0rnrosFBH67mtksrZhJkIfgGB5aSw6T2qozbr8RGHlj5gDMu4X1H+rawQkb1ptWe89eYhdXTCtnTMQAC4U6g=
  - secure: T7VOJkiFl+P1aT1g5R4kxWabKy5IPreZ1MrDJvoWur398BynZd1kA51kqO3stU+at1zSVji86u4BBjgSbv5Yk1e9g29rKZ+tZEQTX00Vo98E6cpR7UH9Iq5UnoecMAfgdhMCLpE/nysaEIjqDMpqFojvbxlpXiXD6Pxu2e57S3IG7mYri5PGrFdvEJrTVGN5rLM/fPZ1UWf1BLKqOTRwCP91zcO4V6LUZZ2xRq6A0WszSTY/8TQ9MiKPVbPNaGwD1oPTq+bc5FG6XcK5xdLkIBmz4tdjD0N8AN3vtNenZs+YUefZKrFZ63hXgSIkte52uqUmyo7o7KWtzONWj3S+eT+EZMxYeD7oTwwaTPsZxyDLs3mrGpnrRj5556W86AUh+6Tq1I9SHilb+xCQ2MVm8am3qCsOYtlFNxVP0dF+/hDVsEm+xVotzlMTCbcI0y2tppRVyw9f3+2qWDVaKTcA2kCTg3E4dIb6e+QpecrRVgPjwKQrfbZQwK6nO+eUg6Dp7jpOVEgRTSVn6hPino2Au3eNZRTXIEl0XPWUzfoMnYzH6UeJS1MABo7CpiRjWgcb0MdDrnJdkeoJdAyKF7niLgkxnNNFMv1j3/Xxe/Vz/EX1H8OKyZkjwzExzezqtx3XPABXGIjz3UgGqCuVf2mu1ztLyylBHeqV6GrVaVyyJws=
