package org.metadatacenter.messaging.dao;

import io.dropwizard.hibernate.AbstractDAO;
import org.hibernate.SessionFactory;
import org.hibernate.query.Query;
import org.metadatacenter.messaging.model.PersistentUser;

import jakarta.persistence.criteria.CriteriaBuilder;
import jakarta.persistence.criteria.CriteriaQuery;
import jakarta.persistence.criteria.Root;

public class PersistentUserDAO extends AbstractDAO<PersistentUser> {

  public PersistentUserDAO(SessionFactory factory) {
    super(factory);
  }

  public Long create(PersistentUser persistentRecipientUser) {
    return persist(persistentRecipientUser).getId();
  }

  public PersistentUser findByCid(String id) {
    CriteriaBuilder builder = currentSession().getCriteriaBuilder();
    CriteriaQuery<PersistentUser> query = builder.createQuery(PersistentUser.class);
    Root<PersistentUser> root = query.from(PersistentUser.class);
    query.select(root);
    query.where(builder.equal(root.get("cid"), id));
    Query<PersistentUser> q = currentSession().createQuery(query);
    return q.uniqueResult();
  }

  /**
   * The row for this cid, inserting one if no request has already.
   * <p>
   * Looking the row up and then inserting it leaves a window: two requests naming the same recipient
   * for the first time both find nothing and both insert, and UK_user_cid then fails the second. The
   * id is generated by the database, so the insert is issued as the entity is persisted rather than
   * at commit, and the violation lands inside the request — where it also leaves the Hibernate
   * session unusable, so it cannot be caught and worked around here.
   * <p>
   * The insert therefore tells the database to do nothing when the row is already there, and the row
   * is read back afterwards: whichever request inserted it, both get the same one. MySQL reports
   * the existing primary key through {@code LAST_INSERT_ID(id)} on the duplicate path, avoiding a
   * second cid lookup that can still see the transaction's earlier repeatable-read snapshot.
   */
  public PersistentUser findOrCreateByCid(String cid) {
    currentSession()
        .createNativeMutationQuery("INSERT INTO `user` (cid) VALUES (:cid)"
            + " ON DUPLICATE KEY UPDATE id = LAST_INSERT_ID(id)")
        .setParameter("cid", cid)
        .executeUpdate();
    return currentSession()
        .createNativeQuery("SELECT * FROM `user` WHERE id = LAST_INSERT_ID()", PersistentUser.class)
        .getSingleResult();
  }
}
