server:
  applicationConnectors:
  - type: http
  adminConnectors:
  - type: http
logging:
  level: INFO
  loggers:
    org.metadatacenter: DEBUG
    org.metadatacenter.server.neo4j.proxy.AbstractNeo4JProxy: INFO
    org.metadatacenter.server.search.elasticsearch: INFO
    org.metadatacenter.server.search.permission: INFO
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
    - type: file
      currentLogFilename: ${CEDAR_HOME}/log/cedar-messaging-server/dropwizard.log
      threshold: ALL
      archive: true
      archivedLogFilenamePattern: ${CEDAR_HOME}/log/cedar-messaging-server/dropwizard-%d.log
      archivedFileCount: 5
      timeZone: UTC
database:
  driverClass: com.mysql.cj.jdbc.Driver
  user: ${CEDAR_MESSAGING_MYSQL_USER}
  password: ${CEDAR_MESSAGING_MYSQL_PASSWORD}
  url: jdbc:mysql://${CEDAR_MESSAGING_MYSQL_HOST}:${CEDAR_MESSAGING_MYSQL_PORT}/${CEDAR_MESSAGING_MYSQL_DB}
  properties:
    createDatabaseIfNotExist: true
    serverTimezone: America/Los_Angeles
    useSSL: false
